swipe:
  3:
    up:
      command: "xdotool key super" # Activity
    down:
      command: "xdotool key super" # Activity
  4:
    left:
      command: "hyprctl dispatch workspace e+1" # History forward
      threshold: 0.5
    right:
      command: "hyprctl dispatch workspace e-1" # History forward
      threshold: 0.5
    up:
      command: "xdotool key ctrl+alt+Down" # Switch to next workspace
    down:
      command: "xdotool key ctrl+alt+Up" # Switch to previous workspace
